{"name": "test_019_04_heroku_ddt", "status": "broken", "statusDetails": {"message": "TypeError: 'NoneType' object is not iterable", "trace": "self = <testcases.test_019_04_heroku_login_ddt.Test_019_04_heroku object at 0x0000012FDAF7D610>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"68fded965409986c31a1ea4e1dc4b222\")>\n\n    def test_019_04_heroku_ddt(self, setup):\n    \n        self.driver=setup ;\n    \n        path=\"D:\\\\PYTHON CT15\\\\FINAL_REVISION\\\\testdata\\\\HEROKU_LOGIN.xlsx\"\n    \n        rows=XUTils.rowCount(path, 'Sheet1') ;\n    \n        for r in range (2, rows+1) :\n    \n            self.driver.get('https://the-internet.herokuapp.com/login') ;\n    \n            username=XUTils.readData(path, 'Sheet1', r, 1) ;\n            password=XUTils.readData(path, 'Sheet1', r, 2) ;\n    \n>           self.driver.find_element(By.XPATH, '//input[@name=\"username\"]').send_keys(username) ;\n\ntestcases\\test_019_04_heroku_login_ddt.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nvenv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py:232: in send_keys\n    Command.SEND_KEYS_TO_ELEMENT, {\"text\": \"\".join(keys_to_typing(value)), \"value\": keys_to_typing(value)}\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nvalue = (None,)\n\n    def keys_to_typing(value: Iterable[AnyKey]) -> List[str]:\n        \"\"\"Processes the values that will be typed in the element.\"\"\"\n        characters: List[str] = []\n        for val in value:\n            if isinstance(val, Keys):\n                # Todo: Does this even work?\n                characters.append(val)\n            elif isinstance(val, (int, float)):\n                characters.extend(str(val))\n            else:\n>               characters.extend(val)\nE               TypeError: 'NoneType' object is not iterable\n\nvenv\\Lib\\site-packages\\selenium\\webdriver\\common\\utils.py:137: TypeError"}, "start": 1709827438656, "stop": 1709827479445, "uuid": "3ba56daf-574f-4eca-a639-187ec947a30c", "historyId": "4a408c807147e3c92861615e7bb980c1", "testCaseId": "4a408c807147e3c92861615e7bb980c1", "fullName": "testcases.test_019_04_heroku_login_ddt.Test_019_04_heroku#test_019_04_heroku_ddt", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_019_04_heroku_login_ddt"}, {"name": "subSuite", "value": "Test_019_04_heroku"}, {"name": "host", "value": "DESKTOP-U7OANNR"}, {"name": "thread", "value": "6396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_019_04_heroku_login_ddt"}]}